export const ADD_PROJECT = 'ADD_PROJECT';
export const SET_PROJECTS = 'SET_PROJECTS';
export const REMOVE_PROJECT = 'REMOVE_PROJECT';
export const SET_USER_VERSIONING_PLATFORM_USERNAME = 'SET_USER_VERSIONING_PLATFORM_USERNAME'
export const SET_OPEN_MODAL = 'SET_OPEN_MODAL';
export const SET_LOADED_PROJECTS = 'SET_LOADED_PROJECTS';
export const SET_SELECTED_PROJECTS = 'SET_SELECTED_PROJECTS';